language: go
sudo: false
go:
  - 1.5.3
env:
  - NSQ_DOWNLOAD=nsq-0.3.5.linux-amd64.go1.4.2 TEMPDIR=".tmp"

services:
  - redis-server
  - mongodb

install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/tools/godep


before_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi
  - FIXED=$(go vet ./... 2>&1); if [ -n "${FIXED}" ]; then echo "go vet failed. $FIXED" && exit 1; fi
  - golint ./...

script:
  - ./verify.sh
  - hack/nsq/test.sh
  - hack/mongo/test.sh
