package uainfo

import (
	"reflect"
	"testing"

	"github.com/MISingularity/deepshare2/api"
)

func TestExtractUserInfoFromUAString(t *testing.T) {
	tests := []struct {
		ua string
		ip string

		expected *UAInfo
	}{
		{
			ua: "Mozilla/5.0 (Linux; U; Android 4.1.1; zh-cn; MI 2A Build/JRO03L) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 MicroMessenger/5.4.0.51_r798589.480 NetType/WIFI",
			ip: "testip",
			expected: &UAInfo{
				Ua:             "Mozilla/5.0 (Linux; U; Android 4.1.1; zh-cn; MI 2A Build/JRO03L) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 MicroMessenger/5.4.0.51_r798589.480 NetType/WIFI",
				Ip:             "testip",
				Os:             "android",
				OsVersion:      "4.1.1",
				Brand:          "xiaomi#mi#2a",
				Browser:        "Android 4.1.1",
				IsWechat:       true,
				IsWeibo:        false,
				IsQQ:           false,
				IsQQBrowser:    false,
				IsFirefox:      false,
				ChromeMajor:    0,
				CannotDeeplink: false,
			},
		},
		{
			ua: "Mozilla/6.0(Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36(KHTML,like Gecko) Version/6.0 Mobile Safari/537.36",
			ip: "testip",
			expected: &UAInfo{
				Ua:             "Mozilla/6.0(Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36(KHTML,like Gecko) Version/6.0 Mobile Safari/537.36",
				Ip:             "testip",
				Os:             "android",
				OsVersion:      "6.0",
				Brand:          "huawei#nxt#al10",
				Browser:        "Android 6.0",
				IsWechat:       false,
				IsWeibo:        false,
				IsQQ:           false,
				IsQQBrowser:    false,
				IsFirefox:      false,
				ChromeMajor:    0,
				CannotDeeplink: true,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; U; Android 6.0; en-gb; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36 (KHTML, like Gecko)Version/4.0 Chrome/37.0.0.0 MQQBrowser/6.3 Mobile Safari/537.36",
			ip: "testip",
			expected: &UAInfo{
				Ua:             "Mozilla/5.0 (Linux; U; Android 6.0; en-gb; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36 (KHTML, like Gecko)Version/4.0 Chrome/37.0.0.0 MQQBrowser/6.3 Mobile Safari/537.36",
				Ip:             "testip",
				Os:             "android",
				OsVersion:      "6.0",
				Brand:          "huawei#nxt#al10",
				Browser:        "QQ Browser Mobile 6.3",
				IsWechat:       false,
				IsWeibo:        false,
				IsQQ:           false,
				IsQQBrowser:    true,
				IsFirefox:      false,
				ChromeMajor:    0,
				CannotDeeplink: false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; U; Android 4.4.4; zh-cn; MI NOTE LTE Build/KTU84P) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025483 Mobile Safari/533.1 MicroMessenger/6.3.8.50_r251a77a.680 NetType/WIFI Language/zh_CN",
			ip: "testip",
			expected: &UAInfo{
				Ua:             "Mozilla/5.0 (Linux; U; Android 4.4.4; zh-cn; MI NOTE LTE Build/KTU84P) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025483 Mobile Safari/533.1 MicroMessenger/6.3.8.50_r251a77a.680 NetType/WIFI Language/zh_CN",
				Ip:             "testip",
				Os:             "android",
				OsVersion:      "4.4.4",
				Brand:          "xiaomi#mi#note#lte",
				Browser:        "QQ Browser Mobile 5.4",
				IsWechat:       true,
				IsWeibo:        false,
				IsQQ:           false,
				IsQQBrowser:    true,
				IsFirefox:      false,
				ChromeMajor:    0,
				CannotDeeplink: false,
			},
		},
		{
			ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H143 QQ/6.1.0.496 Pixel/1080 NetType/WIFI Mem/49",
			ip: "testip",
			expected: &UAInfo{
				Ua:             "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H143 QQ/6.1.0.496 Pixel/1080 NetType/WIFI Mem/49",
				Ip:             "testip",
				Os:             "ios",
				OsVersion:      "8.4",
				Brand:          "-",
				Browser:        "Mobile Safari UIWebView 8.4",
				IsWechat:       false,
				IsWeibo:        false,
				IsQQ:           true,
				IsQQBrowser:    false,
				IsFirefox:      false,
				ChromeMajor:    0,
				CannotDeeplink: false,
			},
		},
		{
			ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0",

			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0",
				Ip:                    "testip",
				Os:                    "mac os x",
				OsVersion:             "10.10",
				Brand:                 "-",
				Browser:               "Firefox 40.0",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             true,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: true,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143 QQ/5.9.5.451 Pixel/750 NetType/WIFI Mem/101",
			ip: "testip",
			expected: &UAInfo{
				Ua:             "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143 QQ/5.9.5.451 Pixel/750 NetType/WIFI Mem/101",
				Ip:             "testip",
				Os:             "ios",
				OsVersion:      "9.1",
				Brand:          "-",
				Browser:        "Mobile Safari UIWebView 9.1",
				IsWechat:       false,
				IsWeibo:        false,
				IsQQ:           true,
				IsQQBrowser:    false,
				IsFirefox:      false,
				ChromeMajor:    0,
				CannotDeeplink: false,
			},
		},
		{
			ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H321 Weibo (iPhone7,2__weibo__5.4.0__iphone__os8.4.1)",
			ip: "testip",
			expected: &UAInfo{
				Ua:             "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H321 Weibo (iPhone7,2__weibo__5.4.0__iphone__os8.4.1)",
				Ip:             "testip",
				Os:             "ios",
				OsVersion:      "8.4.1",
				Brand:          "-",
				Browser:        "Mobile Safari UIWebView 8.4.1",
				IsWechat:       false,
				IsWeibo:        true,
				IsQQ:           false,
				IsQQBrowser:    false,
				IsFirefox:      false,
				ChromeMajor:    0,
				CannotDeeplink: false,
			},
		},
		{
			ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) CriOS/45.0.2454.89 Mobile/12H321 Safari/600.1.4",
			ip: "testip",
			expected: &UAInfo{
				Ua:             "Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) CriOS/45.0.2454.89 Mobile/12H321 Safari/600.1.4",
				Ip:             "testip",
				Os:             "ios",
				OsVersion:      "8.4.1",
				Brand:          "-",
				Browser:        "Chrome Mobile iOS 45.0.2454",
				IsWechat:       false,
				IsWeibo:        false,
				IsQQ:           false,
				IsQQBrowser:    false,
				IsFirefox:      false,
				ChromeMajor:    45,
				CannotDeeplink: false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 SogouSearch Android1.0 version3.0 ",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 SogouSearch Android1.0 version3.0 ",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "Chrome Mobile 45.0.2454",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           45,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: false,
				ForceUseScheme:        true,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; U; Android 6.0; zh-CN; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.9.0.703 U3/0.8.0 Mobile Safari/534.30",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; U; Android 6.0; zh-CN; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.9.0.703 U3/0.8.0 Mobile Safari/534.30",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "UC Browser 10.9.0",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: false,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 MxBrowser/4.5.6.1000 ",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 MxBrowser/4.5.6.1000 ",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "Maxthon Browser Mobile 4.5.6",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        true,
				CannotGetWindowsEvent: false,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 LieBaoFast/3.25.7 ",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 LieBaoFast/3.25.7 ",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "LieBao Browser Mobile 3.25.7",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: true,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; U; Android 6.0; zh-CN; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 OPR/11.1.1.99254 Mobile Safari/537.36 ",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; U; Android 6.0; zh-CN; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 OPR/11.1.1.99254 Mobile Safari/537.36 ",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "Opera Mobile 11.1.1",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: true,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36; 360 Aphone Browser (6.9.9.39) ",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36; 360 Aphone Browser (6.9.9.39) ",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "360 Browser Mobile 6.9.9",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: true,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/6.0(Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36(KHTML,like Gecko) Version/6.0 Mobile Safari/537.36",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/6.0(Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36(KHTML,like Gecko) Version/6.0 Mobile Safari/537.36",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "Android 6.0",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        true,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: false,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/35.0.1916.138 Mobile Safari/537.36 baidubrowser/6.3.20.0 (Baidu; P1 6.0)",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/35.0.1916.138 Mobile Safari/537.36 baidubrowser/6.3.20.0 (Baidu; P1 6.0)",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "Baidu Browser Mobile 6.3.20",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        true,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: true,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 baidubrowser/5.4.5.0 (Baidu; P1 6.0)",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 baidubrowser/5.4.5.0 (Baidu; P1 6.0)",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "Baidu Browser Mobile 5.4.5",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: true,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 baidubrowser/4.0.18.7 (Baidu; P1 6.0)",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 baidubrowser/4.0.18.7 (Baidu; P1 6.0)",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "Baidu Browser Mobile 4.0.18",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: false,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 Mb2345Browser/7.6",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; Android 6.0; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36 Mb2345Browser/7.6",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0",
				Brand:                 "huawei#nxt#al10",
				Browser:               "2345 Browser Mobile 7.6",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: true,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 Twitter for iPhone",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 Twitter for iPhone",
				Ip:                    "testip",
				Os:                    "ios",
				OsVersion:             "9.3.2",
				Brand:                 "-",
				Browser:               "Mobile Safari UIWebView 9.3.2",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsTwitter:             true,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: false,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 [FBAN/FBIOS;FBAV/56.0.0.58.135;FBBV/30582859;FBRV/0;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.3.2;FBSS/2;FBCR/",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 [FBAN/FBIOS;FBAV/56.0.0.58.135;FBBV/30582859;FBRV/0;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.3.2;FBSS/2;FBCR/",
				Ip:                    "testip",
				Os:                    "ios",
				OsVersion:             "9.3.2",
				Brand:                 "-",
				Browser:               "Facebook 56.0.0",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsTwitter:             false,
				IsFacebook:            true,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: false,
				ForceUseScheme:        false,
			},
		},
		{
			ua: "Mozilla/5.0 (Linux; Android 6.0.1; MI 4LTE Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/46.0.2490.76 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/76.0.0.0.27;]",
			ip: "testip",
			expected: &UAInfo{
				Ua:                    "Mozilla/5.0 (Linux; Android 6.0.1; MI 4LTE Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/46.0.2490.76 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/76.0.0.0.27;]",
				Ip:                    "testip",
				Os:                    "android",
				OsVersion:             "6.0.1",
				Brand:                 "xiaomi#mi#4lte",
				Browser:               "Facebook 76.0.0",
				IsWechat:              false,
				IsWeibo:               false,
				IsQQ:                  false,
				IsTwitter:             false,
				IsFacebook:            true,
				IsQQBrowser:           false,
				IsFirefox:             false,
				ChromeMajor:           0,
				CannotDeeplink:        false,
				CannotGoMarket:        false,
				CannotGetWindowsEvent: false,
				ForceUseScheme:        false,
			},
		},
	}
	for _, tt := range tests {
		ui := ExtractUAInfoFromUAString(tt.ip, tt.ua)
		if !reflect.DeepEqual(ui, tt.expected) {
			t.Errorf("extract uainfo from UAString failed, expected: %#v, \ngot: %#v, ua: %v",
				tt.expected,
				ui,
				tt.ua)
		}
	}
}

func TestExtractUserInfoFromReceiverInfo(t *testing.T) {
	tests := []struct {
		ip           string
		uaStr        string
		receiverInfo api.MatchReceiverInfo

		expected *UAInfo
	}{
		{
			ip:    "testip",
			uaStr: "",
			receiverInfo: api.MatchReceiverInfo{
				OS:        "iOS",
				OSVersion: "9.1",
			},

			expected: &UAInfo{
				Ua:        "",
				Ip:        "testip",
				Os:        "ios",
				OsVersion: "9.1",
				Brand:     "-",
				Browser:   "",
				IsWechat:  false,
				IsWeibo:   false,
			},
		},
		{
			ip:    "testip",
			uaStr: "Dalvik/1.6.0 (Linux; U; Android 4.4.4; MI 4LTE MIUI/5.11.19)",
			receiverInfo: api.MatchReceiverInfo{
				OS:        "android",
				OSVersion: "4.4.4",
			},
			expected: &UAInfo{
				Ua:        "Dalvik/1.6.0 (Linux; U; Android 4.4.4; MI 4LTE MIUI/5.11.19)",
				Ip:        "testip",
				Os:        "android",
				OsVersion: "4.4.4",
				Brand:     "xiaomi#mi#4lte",
				Browser:   "",
				IsWechat:  false,
				IsWeibo:   false,
			},
		},
	}

	for _, tt := range tests {
		ui := ExtractUAInfoWithReceiverInfo(tt.ip, tt.uaStr, tt.receiverInfo)
		//bypass the Browser field, since the ua parser has problem when UA starts with Dalvik
		ui.Browser = ""
		if !reflect.DeepEqual(ui, tt.expected) {
			t.Errorf("extract uainfo from receiverInfo failed, expected: %#v, \n got: %#v",
				tt.expected, ui)
		}
	}
}
